In [1]:
import numpy as np
import random

In [2]:
a = np.random.randn(2,3)

In [3]:
a

array([[ 1.32462947, -0.97514371,  1.01009841],
       [-0.72750999,  0.82261331,  0.96881741]])

In [4]:
b=np.where(a>0)
print(b)

(array([0, 0, 1, 1]), array([0, 2, 1, 2]))


In [5]:
print(b)

(array([0, 0, 1, 1]), array([0, 2, 1, 2]))


In [53]:
import numpy as np
list1 = [[-1,2,0,4], [4,-3,5]]

In [54]:
def clear_list(x):
    for item in x:
        for i in item:
            print(i)
            index = item.index(i)
            print(index,'xx' , i)
            if i<=0: 
                item.pop(index)
    return x

In [55]:
y = clear_list(list1)

-1
0 xx -1
0
1 xx 0
4
0 xx 4
-3
1 xx -3


In [3]:
list1 = [[-11,12,0,14], [4,-3,15]]
print(list1)

[[-11, 12, 0, 14], [4, -3, 15]]


In [1]:
def square_list(lst):
    result = []
    for inner_list in lst:
        squared_inner_list = []
        for element in inner_list:
            if element >0:
                squared_inner_list.append(element **2)
        result.append(squared_inner_list)
    return result

In [4]:
print(square_list(list1))

[[144, 196], [16, 225]]


In [ ]:
def square_element(lst):
    